version: "3.8"
services:
  db:
    image: cloudpi1/cloudpi:Cloudpi_db_v1.0.54

    container_name: cloudpi-db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - cloudpi-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h cloudpi-db  -uadmin -pAWSGCPPI_2k23  || exit 1",
        ]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 90s # ⬅️ Increased from 50s to 90s

    env_file:
      - .env
  app:
    image: cloudpi1/cloudpi:Cloudpi_v1.0.54
    container_name: cloudpi-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "6379:6379" # Redis
      - "8088:8088" # Superset
      - "3000:3000" # React App
      - "5005:5005" # Flask App
      - "5001:5001" # Node App
      - "443:443" # HTTPS
      - "80:80" # HTTP
    networks:
      - cloudpi-network
    env_file:
      - .env
    environment:
      HOST: ${HOST:-localhost}
      LOCALSTACK_ENDPOINT: ${LOCALSTACK_ENDPOINT}
    volumes:
      - redis_data:/var/lib/redis
      - ./certs:/home/certs/
    command: ["/bin/bash", "/app/entrypoint.sh"]

volumes:
  mysql_data:
  redis_data:
networks:
  cloudpi-network:
    driver: bridge
